[package]
name = "reddit-cli"
version = "0.1.0"
authors = ["Hyde46 <denis.heid@protonmail.com>"]
edition = "2018"


[dependencies]
curl = "0.4.29"
webbrowser = "0.5.2"
tiny_http = "0.7"
rand = "0.7.3" 
serde = { version = "1.0.110", features = ["derive"] }
serde_json = "1.0"
